<script type="text/javascript" src="js/jquery-3.3.1.min.js"></script>
<script type="text/javascript" src="js/bootstrap.min.js"></script>
<script type="text/javascript" src="js/mdb.min.js"></script>
<script type="text/javascript" src="js/popper.min.js"></script>
<script type="text/javascript" src="js/jquery-ui.min.js"></script>
<script type="text/javascript" src="js/table.jquery.js"></script>
<script type="text/javascript" src="js/table.js"></script>
<script type="text/javascript" src="js/form.js"></script>
<script type="text/javascript" src="js/charts.js"></script>
<script type="text/javascript" src="js/passreset.js"></script>
<script type="text/javascript" src="js/bootstrap.js"></script>
